name: ci-frontend-workflow

on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        
  # Automatic trigger on push events to the main branch
  pull_request:
    branches:
      - main
    paths:
      - 'starter/backend/**'     

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Cache pipenv
      uses: actions/cache@v4
      id: cache-pipenv
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-pipenv-${{ hashFiles('${{ vars.BACKEND_APP_DIR }}/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv
          
    - name: Install pipenv
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pipenv wheel

    - name: Install Dependencies
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
        pipenv install --system --deploy --dev
