name: ci-frontend-workflow
on:
  pull_request:
    branches:
      - master
    paths:
      - starter/frontend/**
  workflow_dispatch: null
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: ./.github/workflows/npm-setup.yaml
        with:
          working-directory: starter/frontend
      - name: Run lint
        working-directory: starter/frontend
        run: npm run lint
