name: ci-frontend-workflow
on:
  pull_request:
    branches:
      - master
    paths:
      - starter/frontend/**
  workflow_dispatch: null
  
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/npm-setup.yml
        with:
          working-directory: starter/frontend
      - if: '${{ steps.cache-npm.outputs.cache-hit != ''true'' }}'
        name: List the state of node modules
        continue-on-error: true
        run: npm --prefix starter/frontend list
      - name: Install dependencies
        run: npm --prefix starter/frontend install
        
  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: ./.github/workflows/npm-setup.yml
        with:
          working-directory: starter/frontend
      - name: Run lint
        working-directory: starter/frontend
        run: npm run lint
