name: ci-frontend-workflow

on:
  # 1. Is triggered on pull_requests events against the main branch
  pull_request:
    branches:
      - master
    # a. Only when code in the frontend application changes  
    paths:
      - 'starter/frontend/**'  

  # 2. Can be run on-demand (i.e. manually without needing to push code)
  workflow_dispatch:    

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        
    # Cache node modules
    - name: Cache node modules
      id: cache
      uses: actions/cache@v3
      with:
        path: ~/starter/frontend/node_modules  # Cache node_modules within the correct directory
        key: ${{ runner.os }}-node-modules-${{ hashFiles('starter/frontend/**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-
          
   # Install dependencies
    - name: Install dependencies
      working-directory: starter/frontend  # Run npm install in the correct directory
      run: npm install    
