name: ci-frontend-workflow

on:
  # 1. Is triggered on pull_requests events against the main branch
  pull_request:
    branches:
      - master
    # a. Only when code in the frontend application changes  
    paths:
      - 'starter/frontend/**'  


  # 2. Can be run on-demand (i.e. manually without needing to push code)
  workflow_dispatch:    

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        
    # clear cache  
    - run: cd frontend && npm cache clean --force
    # install dependencies
    - run: cd frontend && npm ci
    
