name: ci-frontend-workflow

on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:
    inputs:
      environment:
        type: environment

  # Automatic trigger on push events to the main branch
  pull_request:
    branches:
      - main
    paths:
      - 'starter/frontend/**' 

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
    - run: echo "The environment is ${{ github.event.inputs.environment }}"
    - run: echo "The APP_DIR is ${{ env.APP_DIR }}"
    - run: echo "The NODE_VERSION is ${{ env.NODE_VERSION }}"
    - run: echo "The REACT_APP_MOVIE_API_URL is ${{ env.REACT_APP_MOVIE_API_URL }}"
        
