name: ci-frontend-workflow
on:
  pull_request:
    branches:
      - master
    paths:
      - starter/frontend/**
  workflow_dispatch:
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: List files and directories
        run: ls -R
      - uses: ./.github/workflows/npm-setup.yaml
        with:
          working-directory: starter/frontend
      - name: Run lint
        run: npm --prefix starter/frontend run lint
