name: ci-frontend-workflow

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        
  # Automatic trigger on PR
  pull_request:
    branches:
      - main
    paths:
      - 'starter/frontend/**'

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'udacity' }}
    steps:
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3
      
    # Setup Node
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ vars.NODE_VERSION }}
      
    # Load NPM cache
    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('${{ vars.APP_DIR }}/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    # Print missing dependencies
    - if: '${{ steps.cache-npm.outputs.cache-hit != ''true'' }}'
      name: List the state of node modules
      continue-on-error: true
      run: npm --prefix ${{ vars.APP_DIR }} list

    # Install dependencies
    - name: Install dependencies
      run: npm --prefix ${{ vars.APP_DIR }} install
      
  lint:
    needs: [ setup ]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'udacity' }}
    steps:
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3
      
    # Setup Node
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ vars.NODE_VERSION }}
      
    # Load NPM cache
    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('${{ vars.APP_DIR }}/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    # Run lint
    - name: Run lint
      run: npm --prefix ${{ vars.APP_DIR }} run lint .

  test:
    needs: [ setup ]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'udacity' }}
    steps:
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3
      
    # Setup Node
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ vars.NODE_VERSION }}
      
    # Load NPM cache
    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('${{ vars.APP_DIR }}/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    # Run tests
    - name: Run lint
      run: npm --prefix ${{ vars.APP_DIR }} run test

  build:
    needs: [ lint, test ]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'udacity' }}
    steps:
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3
      
    # Setup Node
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ vars.NODE_VERSION }}
      
    # Load NPM cache
    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('${{ vars.APP_DIR }}/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Build Application
      run: |
        cd ${{ vars.APP_DIR }} && docker build --build-arg REACT_APP_MOVIE_API_URL=${{ vars.REACT_APP_MOVIE_API_URL }} .
