name: ci-frontend-workflow

on:
  # Is triggered on pull_requests events against the main branch
  pull_request:
    branches:
      - main

  # 2. Can be run on-demand (i.e. manually without needing to push code)
  workflow_dispatch:    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Print a message
      run: echo "Hello, world!"