name: ci-frontend-workflow

on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:
    inputs:
      environment:
        type: environment

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Print the environment
        run: echo "The environment is ${{ inputs.environment }}"
      - name: Print environment variables
        run: |
          echo "The APP_DIR is ${{ vars.APP_DIR }}"
          echo "The NODE_VERSION is ${{ vars.NODE_VERSION }}"
          echo "The REACT_APP_MOVIE_API_URL is ${{ vars.REACT_APP_MOVIE_API_URL }}"
        
