name: "Use Composite Action"
on:
  workflow_call:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Use Composite Action
        uses: ./.github/workflows/test.yaml
        with:
          example-input: "World"
      - name: Display Output
        run: echo "Output was"
